### ISSUE TITLE
Files don't load when active.

### ISSUE THREAD

**Issue by kai-schmid** [jgraph/drawio-nextcloud#14]
If the drow io plugin is active, the Folders in the File App don't load anymore. I am currently running NC 25.0.2

[webdav] Fehler: Error: Call to undefined method OCA\Drawio\AppConfig::getPreviews() at <<closure>>

 0. /var/www/nextcloud/lib/private/Preview/ProviderV1Adapter.php line 48
    OCA\Drawio\Preview\DrawioPreview->isAvailable()
 1. /var/www/nextcloud/lib/private/PreviewManager.php line 257
    OC\Preview\ProviderV1Adapter->isAvailable()
 2. /var/www/nextcloud/apps/dav/lib/Connector/Sabre/FilesPlugin.php line 353
    OC\PreviewManager->isAvailable()
 3. /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/PropFind.php line 95
    OCA\DAV\Connector\Sabre\FilesPlugin->OCA\DAV\Connector\Sabre\{closure}("*** sensitive parameters replaced ***")
 4. /var/www/nextcloud/apps/dav/lib/Connector/Sabre/FilesPlugin.php line 354
    Sabre\DAV\PropFind->handle()
 5. /var/www/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php line 89
    OCA\DAV\Connector\Sabre\FilesPlugin->handleGetProperties()
 6. /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 1052
    Sabre\DAV\Server->emit()
 7. /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 984
    Sabre\DAV\Server->getPropertiesByNode()
 8. /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 1662
    Sabre\DAV\Server->getPropertiesIteratorForPath()
 9. /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 1647
    Sabre\DAV\Server->writeMultiStatus()
10. /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php line 346
    Sabre\DAV\Server->generateMultiStatus()
11. /var/www/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php line 89
    Sabre\DAV\CorePlugin->httpPropFind()
12. /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 472
    Sabre\DAV\Server->emit()
13. /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 253
    Sabre\DAV\Server->invokeMethod()
14. /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 321
    Sabre\DAV\Server->start()
15. /var/www/nextcloud/apps/dav/lib/Server.php line 360
    Sabre\DAV\Server->exec()
16. /var/www/nextcloud/apps/dav/appinfo/v2/remote.php line 35
    OCA\DAV\Server->exec()
17. /var/www/nextcloud/remote.php line 171
    require_once("/var/www/nextcl ... p")

PROPFIND /remote.php/dav/files/kai.schmid@drk-holzgerlingen-altdorf.de/
from 84.60.59.151 by kai.schmid@drk-holzgerlingen-altdorf.de at 2023-01-03T20:10:51+00:00

**Comment by fancycode** [comment]
Just noticed the same issue. Looks like the method is called `GetPreviews`, not `getPreviews`:
https://github.com/jgraph/drawio-nextcloud/blob/58592bddf7c2fb4f9dbb6f06b890a1a29be68347/drawio/lib/appconfig.php#L166

As a workaround you could either change the method name to `getPreviews` or update the callers to use the uppercase `G`.

**Comment by marcatsmci** [comment]
Same problem: just try to enter the directory and the message **This directory is unavailable, please check the logs or contact the administrator** appears and the directory is inaccessible.

Deactivating the application allows you to see the contents of the directory again.

Debian 11.6 / PHP 8.1 / Nextcloud Hub 3 (25.0.2) / Draw.io 2.0.1

**Comment by m-mohamedin** [comment]
Fixed in v2.0.2
Thanks for the report

**Comment by kleener** [comment]
I still have the same problem:

[index] Fehler: Exception: Call to undefined method OCA\Drawio\AppConfig::GetPreviews() in file '/var/www/nextcloud/apps/drawio/lib/Preview/DrawioPreview.php' line 68 at <<closure>>

0. /var/www/nextcloud/lib/private/AppFramework/App.php line 172
   OC\AppFramework\Http\Dispatcher->dispatch()
1. /var/www/nextcloud/lib/private/Route/Router.php line 298
   OC\AppFramework\App::main()
2. /var/www/nextcloud/lib/base.php line 1047
   OC\Route\Router->match()
3. /var/www/nextcloud/index.php line 36
   OC::handleRequest()

**Comment by marcatsmci** [comment]
Version 2.0.2 does not fix the problem !

```

[webdav] Error: Error: Call to undefined method OCA\Drawio\AppConfig::getPreviews() at <<closure>>

 0. /var/www/nextcloud/lib/private/Preview/ProviderV1Adapter.php line 48
    OCA\Drawio\Preview\DrawioPreview->isAvailable()
 1. /var/www/nextcloud/lib/private/PreviewManager.php line 257
    OC\Preview\ProviderV1Adapter->isAvailable()
 2. /var/www/nextcloud/apps/dav/lib/Connector/Sabre/FilesPlugin.php line 353
    OC\PreviewManager->isAvailable()
 3. /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/PropFind.php line 95
    OCA\DAV\Connector\Sabre\FilesPlugin->OCA\DAV\Connector\Sabre\{closure}("*** sensitive parameters replaced ***")
 4. /var/www/nextcloud/apps/dav/lib/Connector/Sabre/FilesPlugin.php line 354
    Sabre\DAV\PropFind->handle()
 5. /var/www/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php line 89
    OCA\DAV\Connector\Sabre\FilesPlugin->handleGetProperties()
 6. /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 1052
    Sabre\DAV\Server->emit()
 7. /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 984
    Sabre\DAV\Server->getPropertiesByNode()
 8. /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 1662
    Sabre\DAV\Server->getPropertiesIteratorForPath()
 9. /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 1647
    Sabre\DAV\Server->writeMultiStatus()
10. /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php line 346
    Sabre\DAV\Server->generateMultiStatus()
11. /var/www/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php line 89
    Sabre\DAV\CorePlugin->httpPropFind()
12. /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 472
    Sabre\DAV\Server->emit()
13. /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 253
    Sabre\DAV\Server->invokeMethod()
14. /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 321
    Sabre\DAV\Server->start()
15. /var/www/nextcloud/apps/dav/lib/Server.php line 360
    Sabre\DAV\Server->exec()
16. /var/www/nextcloud/apps/dav/appinfo/v2/remote.php line 35
    OCA\DAV\Server->exec()
17. /var/www/nextcloud/remote.php line 171
    require_once("/var/www/nextcl ... p")

PROPFIND /remote.php/dav/files/admin/Infra-Sch%C3%A9mas
from 194.230.158.76 by admin at 2023-01-05T08:19:10+00:00


```

**Comment by marcatsmci** [comment]
Please, reopen this issue... @m-mohamedin

**Comment by davidjgraph** [comment]
Please open a new issue with environment, recreation steps and output.
